### ISSUE TITLE
Jupiter and Moon frames are failing

### ISSUE THREAD

**Issue by jorgepiloto** [poliastro/validation#27]
Something has changed, and the Jupiter and Moon frame conversion tests are no longer passing 😨
There is no new release of Orekit and it looks like this is failing since this pull request in poliastro (15 days ago as of today):

* https://github.com/poliastro/poliastro/pull/1190

Just in case, also citing here this pull also:

* https://github.com/poliastro/poliastro/pull/1223
 
 as it is also related to a recent bodies refactor. Needs further investigation....

**Comment by Yash-10** [comment]
Hi @jorgepiloto, I did a quick analysis of poliastro/poliastro#1190.

I think that pull request might be a strong suspect for these numerical errors. My thoughts follow:

Taking a look at https://github.com/poliastro/poliastro/blob/main/tests/test_frames.py, it looks like the feature of calculating rotational elements at a particular epoch is not being tested anywhere (`from_equatorial` and `to_equatorial` are the only two method which use `rot_elements_at_epoch`) and there seems to be no evidence of it being tested in any other test. As a result, the change in that PR might not have catched up in the tests, both the local and CI tests. Since this repository checks for validations that might not get necessarliy picked up in poliastro's tests, such errors might have been evident here.

Do you think this might be a reason for this, or am I missing something?

Looking at this, it seems to me that solving poliastro/poliastro#1236 might be a good first step. I think the coverage reports in PRs check for coverage diffs and not the absolute coverage of already existing files. For example, the coverage for frames files:

```
src/poliastro/frames/fixed.py                                          109      3      4      0    97%
src/poliastro/core/fixed.py                                             96     76      0      0    21%
```


and hence it would be good to address that issue too?

Thanks!

**Comment by jorgepiloto** [comment]
Hi @Yash-10, you are right. The tests cases from poliastro did not catch up the issue, which I found it to be *trigonometric arguments are being passed in degrees and not in radians* 😅

**Comment by jorgepiloto** [comment]
This was solved in https://github.com/poliastro/poliastro/pull/1239. Closing...
